# Generated by Django 3.2.5 on 2021-11-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Task_Type', models.TextField()),
                ('semester', models.TextField()),
                ('Attachment', models.ImageField(upload_to='media')),
            ],
        ),
    ]
