# Generated by Django 3.2.5 on 2021-11-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0002_auto_20211115_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Attachment',
            new_name='Image_Attachment',
        ),
        migrations.AddField(
            model_name='student',
            name='File_Attachment',
            field=models.FileField(blank=True, null=True, upload_to='%d/%m/%y'),
        ),
        migrations.AddField(
            model_name='student',
            name='Year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
