# Generated by Django 3.2.5 on 2021-11-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0003_auto_20211115_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Large_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
