# Generated by Django 3.2.5 on 2021-11-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0004_student_large_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Assignment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
