# Generated by Django 3.2.5 on 2021-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0006_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Task_Type',
            field=models.CharField(blank=True, choices=[('assignment', 'Assignment'), ('classwork', 'Classwork'), ('test', 'Test')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.CharField(blank=True, choices=[('1 year', '1st year'), ('2 year', '2nd year'), ('3 year', '3rd year'), ('4 year', '4th year')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, choices=[('CSE 201', 'CSE 201 Programming Concepts (Advanced Programming)'), ('CSE 211', 'CSE 211 Computer Programming using VB.NET'), ('CSE 221', 'CSE 221 System Programming Concept (C, C++) (Embedded Systems)'), ('CSE 231', 'CSE 231 Computer Application Packages II (Mobile Computing)'), ('CSE 241', 'CSE 241 Structured Query Language I (Cyber Security)'), ('CSE 251', 'CSE 251 Relational Database Management Systems (RDBMS) '), ('ENT 201', 'ENT 201 Entrepreneurship Development')], max_length=300, null=True),
        ),
    ]
