# Generated by Django 3.2.5 on 2021-11-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0012_rename_semester_student_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Large_text',
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
