# Generated by Django 3.2.5 on 2021-11-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0013_auto_20211118_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Description',
            new_name='Task_description',
        ),
    ]
